name: Second Workflow

on: 
 push:
 pull_request:
 workflow_dispatch:
 schedule:
    - cron: "*/5 * * * *"
jobs:

 echo-print:
  runs-on: ubuntu-latest
  
  steps:
      - run: echo "${{ github.event_name }"
